### PR TITLE
Change animated properties to make use of hardware acceleration

### PR DESCRIPTION
**Pull request by nicolasmn**
Just replaced all occurrences of `margin-left` and `margin-top` with `transform: translateX` and `transform: translateY` respectively to increase performance.

### CODE REVIEW

**Comment by nicolasmn** [comment]
Also fixes #43

**Comment by CHEWX** [comment]
This really needs merging in. Using `margin` animations is not good.

**Comment by aamirafridi** [comment]
Looks good. Is all tested (with all options)
The only problem I see is that transform has no support for IE11 below. So this needs a fallback :|

**Comment by nicolasmn** [comment]
According to Caniuse 2D transforms are well supported back to IE9, see https://caniuse.com/#feat=transforms2d.
In addition jQuery will add vendor prefixes automatically, but that depends on the version used I guess.

**Comment by aamirafridi** [comment]
@nicolasmn for IE9, you need -ms- prefix
image

**Comment by nicolasmn** [comment]
@aamirafridi That's correct. As I wrote, jQuery will add these prefixes automatically (if you are using a version with IE9 support).

**Pull request merged**
